// <auto-generated />
using System;
using HelpURL.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpURL.Infra.Data.Migrations
{
    [DbContext(typeof(HelpURLContext))]
    [Migration("20230419191046_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HelpURL.Domain.Entities.URL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("HelpURL.Domain.Entities.URL", b =>
                {
                    b.OwnsOne("HelpURL.Domain.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("URLId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Descricao");

                            b1.HasKey("URLId");

                            b1.ToTable("Urls");

                            b1.WithOwner()
                                .HasForeignKey("URLId");
                        });

                    b.OwnsOne("HelpURL.Domain.ValueObjects.URLTexto", "URLTexto", b1 =>
                        {
                            b1.Property<Guid>("URLId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("URL");

                            b1.HasKey("URLId");

                            b1.ToTable("Urls");

                            b1.WithOwner()
                                .HasForeignKey("URLId");
                        });

                    b.Navigation("Descricao")
                        .IsRequired();

                    b.Navigation("URLTexto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
